USE swiggy ;


-- 1. Select all records from the restaurants table
SELECT * FROM restaurants ;

-- 2.Rank every restaurant from most expensive to least expensive
SELECT *, RANK()
OVER(ORDER BY COST DESC) AS exp
FROM restaurants ;

-- 3.Rank every restaurant from most visited to least visited
SELECT *, RANK()
OVER(ORDER BY rating_count DESC) AS visited
FROM restaurants ;

-- 4.Rank every restaurant from most expensive to least expensive as per their city
SELECT *, RANK()
OVER(PARTITION BY city ORDER BY cost DESC) AS ranking_per_city
FROM restaurants ;

-- 5.Dense-rank every restaurant from most expensive to least expensive as per their city
SELECT *, DENSE_RANK()
OVER(PARTITION BY city ORDER BY cost DESC) AS ranK_per_city
FROM restaurants ;

-- 6.Row - number every restaurant from most expensive to least expensive as per their city
SELECT *, ROW_NUMBER()
OVER(PARTITION BY city ORDER BY cost DESC) AS r_number
FROM restaurants ;

-- 7. Rank the restaurant based on their prices (most to least expensive) 
-- as per cuisine using rank, dense_rank, and row_number.
SELECT name, cost,cuisine, RANK()
OVER(PARTITION BY cuisine ORDER BY cost DESC) AS e_price
FROM restaurants ;

-- DENSE-RANK
SELECT name, cost, cuisine, DENSE_RANK()
OVER(PARTITION BY cuisine ORDER BY cost DESC) AS e_price
FROM restaurants ;

-- ROW number
SELECT name, cost, cuisine, ROW_NUMBER()
OVER(PARTITION BY cuisine ORDER BY cost DESC) AS e_price
FROM restaurants ;

-- 8. Find top 5 restaurants of every city as per their revenue.
WITH t1 AS (
    SELECT *, cost * rating_count AS revenue
    FROM restaurants
),
t2 AS (
    SELECT name,
           city,
           revenue,
           DENSE_RANK() OVER (
               PARTITION BY city
               ORDER BY revenue DESC
           ) AS rank_revenue
    FROM t1
)
SELECT *
FROM t2
WHERE rank_revenue <= 5;

-- 9. Find top 5 restaurants of every cuisine as per their revenue
SELECT *
FROM (
    SELECT name,
           cuisine,
           cost * rating_count AS revenue,
           ROW_NUMBER() OVER (
               PARTITION BY cuisine
               ORDER BY cost * rating_count DESC
           ) AS rank_revenue
    FROM restaurants
) t
WHERE rank_revenue <= 5;


-- 10.List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine.
SELECT cuisine, SUM(revenue) AS total_revenue
FROM (
    SELECT 
        name,
        cuisine,
        cost * rating_count AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY cuisine
            ORDER BY cost * rating_count DESC
        ) AS rank_revenue
    FROM restaurants
) t
WHERE rank_revenue <= 5
GROUP BY cuisine
ORDER BY total_revenue DESC
LIMIT 5;

-- 11.List the top 5 cities as per the revenue generated by top 5 restaurants of every city.
SELECT city, SUM(revenue) AS total_revenue
FROM (
    SELECT 
        name,
        city,
        cost * rating_count AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY city
            ORDER BY cost * rating_count DESC
        ) AS rank_revenue
    FROM restaurants
) t
WHERE rank_revenue <= 5
GROUP BY city
ORDER BY total_revenue DESC
LIMIT 5;

-- 12. Find the total revenue generated by top 1% restaurants
USE swiggy ;
WITH ranked AS (
    SELECT 
        name,
        cuisine,
        cost * rating_count AS revenue,
        ROW_NUMBER() OVER (ORDER BY cost * rating_count DESC) AS row_num,
        COUNT(*) OVER () AS total_restaurants
    FROM restaurants
)
SELECT SUM(revenue) AS total_top_1_percent_revenue
FROM ranked
WHERE row_num <= total_restaurants * 0.01;

-- 13. Find the total revenue generated by top 20% restaurants.
WITH ranked AS (
    SELECT 
        name,
        cuisine,
        cost * rating_count AS revenue,
        ROW_NUMBER() OVER (ORDER BY cost * rating_count DESC) AS row_num,
        COUNT(*) OVER () AS total_restaurants
    FROM restaurants
)
SELECT SUM(revenue) AS total_top_20_percent_revenue
FROM ranked
WHERE row_num <= total_restaurants * 0.2;

-- 14. What percentage of total revenue is generated by top 20% restaurants?
WITH ranked AS (
    SELECT 
        cost * rating_count AS revenue,
        ROW_NUMBER() OVER (ORDER BY cost * rating_count DESC) AS row_num,
        COUNT(*) OVER () AS total_restaurants,
        SUM(cost * rating_count) OVER () AS total_revenue
    FROM restaurants
)
SELECT 
    (SUM(revenue) * 100.0) / MAX(total_revenue) AS percentage_top_20_revenue
FROM ranked
WHERE row_num <= total_restaurants * 0.2;